### PR TITLE
fix: don't use deprecated getWithDefault (fix #286)

### LINKED ISSUE #286: DEPRECATION: getWithDefault
[RFC554](https://github.com/emberjs/rfcs/blob/master/text/0554-deprecate-getwithdefault.md) deprecates `getWithDefault` ([change landed in 3.21](https://blog.emberjs.com/2020/09/02/ember-3-21-released.html))

This addon uses it here:
https://github.com/mansona/ember-cli-notifications/blob/cd350288ddf5d7f8652bbebdf2ce9600b1050eef/addon/services/notifications.js#L5
https://github.com/mansona/ember-cli-notifications/blob/cd350288ddf5d7f8652bbebdf2ce9600b1050eef/addon/services/notifications.js#L29-L30

### PR DESCRIPTION
**Pull request by jacobq**
Alternatively, the [`??` (nullish coalescing) operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) could be used instead, but this seemed a reasonable solution.

Fixes #286

### CODE REVIEW

**Review by Turbo87 — APPROVED** [review]

**Review by mansona — APPROVED** [review]
This looks great 👍

**Comment by mansona** [comment]
I would probably have gone with the nullish coalescing operator if it were me but this PR is fine as it is 👍  thanks for doing this 🎉

**Comment by mansona** [comment]
fixed in 6.3.1 🎉

File: addon/services/notifications.js [hunk 1]
```diff
@@ -23,11 +23,12 @@ export default Service.extend({
...
     }
 
+    const defaultAutoClear = typeof globals.autoClear === 'boolean' ? globals.autoClear : false;
     const notification = EmberObject.create({
       message: options.message,
       type: options.type || 'info',
-      autoClear: (isEmpty(options.autoClear) ? getWithDefault(globals, 'autoClear', false) : options.autoClear),
-      clearDuration: options.clearDuration || getWithDefault(globals, 'clearDuration', 3200),
+      autoClear: (isEmpty(options.autoClear) ? defaultAutoClear : options.autoClear),
+      clearDuration: options.clearDuration || globals.clearDuration || 3200,
```
Comment (jacobq) [inline addon/services/notifications.js:31]: Would `globals.clearDuration` ever be `0`? I suppose in that case this PR changes the behavior (overwrites it with 3200).

Comment (mansona) [reply addon/services/notifications.js:31]: ah that's a good point 🤔  I guess maybe someone could define it as `0` for tests so I guess this is technically different then

Do you want to try a PR using nullish coalescing here and I can release it as another patch? 👍

Comment (jacobq) [reply addon/services/notifications.js:31]: Sure, I'll throw one up here later today if you haven't already fixed it by then.
