### PR TITLE
Make inclusion of the font-awesome assets in project configurable

### LINKED ISSUE #52: font-awesome error when updating from 2.0.0 to 2.1.0
When I update the `ember-cli-notifications` to `2.1.0` from `2.0.0` I get the following error:

```
Merge error: file fonts/fontawesome-webfont.eot exists in /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-EswIeip1.tmp and /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-dLNYnfA4.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
Error: Merge error: file fonts/fontawesome-webfont.eot exists in /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-EswIeip1.tmp and /home/cesar/src/bootenv/bootenv-webapp/tmp/funnel-output_path-dLNYnfA4.tmp
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
  at mergeRelativePath (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:98:21)
  at mergeRelativePath (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:122:17)
  at /home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/broccoli-merge-trees/index.js:23:5
  at lib$rsvp$$internal$$tryCatch (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
  at lib$rsvp$$internal$$invokeCallback (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
  at lib$rsvp$$internal$$publish (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
  at lib$rsvp$asap$$flush (/home/cesar/src/bootenv/bootenv-webapp/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
```

I have `"font-awesome": "~4.4.0"` defined on my `bower.json` file. Is there anything I should change elsewhere to make this work? How can I start debugging this?

Thanks!

### PR DESCRIPTION
**Pull request by cesarizu**
This PR implements a `incudeFontAwesome` option on `ember-cli-config.js` (or `Brocfile.js`) to enable or disable inclusion. Currently the default is **not** to include `font-awesome` but if needed I could set it to include by default and update this PR.

Fixes #52

### CODE REVIEW

File: blueprints/ember-cli-notifications/index.js [hunk 1]
```diff
@@ -7,9 +7,11 @@ module.exports = {
   // Use config to determine whether Font Awesome is imported into consuming app
   afterInstall: function(app) {
     var projectConfig = this.project.config(app.env);
-    var config = projectConfig['ember-cli-notifications'];
+    var config = projectConfig['ember-cli-notifications'] ||
+                 app.options['ember-cli-notifications'] ||
+                 { includeFontAwesome: false };
```
Comment (ynnoj) [inline blueprints/ember-cli-notifications/index.js:11]: I'd actually prefer if the default value was `true`. That way the add-on will work as designed out the box with no configuration.

File: index.js [hunk 2]
```diff
@@ -12,9 +12,11 @@ module.exports = {
 
   importFontAwesome: function(app) {
     var projectConfig = this.project.config(app.env);
-    var config = projectConfig['ember-cli-notifications'];
+    var config = projectConfig['ember-cli-notifications'] ||
+                 app.options['ember-cli-notifications'] ||
+                 { includeFontAwesome: false };
```
Comment (ynnoj) [inline index.js:16]: Same as https://github.com/Blooie/ember-cli-notifications/pull/53/files#r35857934.

File: blueprints/ember-cli-notifications/index.js [hunk 3]
```diff
@@ -7,9 +7,11 @@ module.exports = {
...
 
-    if (!config || config.icons !== 'bootstrap') {
+    if (config.includeFontAwesome) {
```
Comment (ynnoj) [inline blueprints/ember-cli-notifications/index.js:13]: We shouldn't add font-awesome into the consuming application's Bower dependencies if the config is set to use Bootstrap flavour icons. 

`if (config.includeFontAwesome && config.icons !== 'bootstrap')`

File: index.js [hunk 4]
```diff
@@ -12,9 +12,11 @@ module.exports = {
...
 
-    if (!config || config.icons !== 'bootstrap') {
+    if (config.includeFontAwesome) {
```
Comment (ynnoj) [inline index.js:18]: Same as https://github.com/Blooie/ember-cli-notifications/pull/53/files#r35858099.

File: blueprints/ember-cli-notifications/index.js [hunk 5]
```diff
@@ -7,9 +7,11 @@ module.exports = {
   // Use config to determine whether Font Awesome is imported into consuming app
   afterInstall: function(app) {
     var projectConfig = this.project.config(app.env);
-    var config = projectConfig['ember-cli-notifications'];
+    var config = projectConfig['ember-cli-notifications'] ||
+                 app.options['ember-cli-notifications'] ||
```
Comment (ynnoj) [inline blueprints/ember-cli-notifications/index.js]: Why separate? Let's use the config object in the application's `environment.js`.

File: index.js [hunk 6]
```diff
@@ -12,9 +12,11 @@ module.exports = {
 
   importFontAwesome: function(app) {
     var projectConfig = this.project.config(app.env);
-    var config = projectConfig['ember-cli-notifications'];
+    var config = projectConfig['ember-cli-notifications'] ||
+                 app.options['ember-cli-notifications'] ||
```
Comment (ynnoj) [inline index.js]: Same as https://github.com/Blooie/ember-cli-notifications/pull/53/files#r35858265.

**Comment by ynnoj** [comment]
Hey @cesarizu! Sorry you've had trouble with the latest release. I've added a few notes, but otherwise happy to merge this once addressed.

File: README.md [hunk 7]
```diff
@@ -92,7 +92,16 @@ Include this snippet in your Handlebars template to display the notifications.
...
+By default, [Font Awesome] is used by the addon for the message type icons. To include the [Font Awesome] assets in your app add the following to your applications `ember-cli-build.js` (or `Brocfile.js`) file.
+
+```js
+  var app = new EmberApp(defaults, {
+    ...
+    'ember-cli-notifications': {
+      includeFontAwesome: true
+    }
+  });
+```
```
Comment (ynnoj) [inline README.md:105]: This will need updating to reflect changes in comments below once addressed.

File: blueprints/ember-cli-notifications/index.js (hunk 1 above)
Comment (cesarizu) [inline blueprints/ember-cli-notifications/index.js]: By looking at the 2.0.0 code [here](https://github.com/Blooie/ember-cli-notifications/blob/v2.0.0/index.js#L13) it seems that it doesn't include `font-awesome` by default. Also the [README](https://github.com/Blooie/ember-cli-notifications/blob/v2.0.0/README.md#font-awesome) states that.

I believe that this should be considered a regression and left `false` by default to avoid breaking SemVer so that existing apps that update don't have errors.

On the other hand I understand that it would be nice for the addon to work out of the box when installed stand-alone. I don't think that asking the user to define `'includeFontAwesome': true` or having an extra `ember install ember-cli-font-awesome` is too much to ask for a developer and if it's clear in the README then I don't see much of a problem there.

File: blueprints/ember-cli-notifications/index.js (hunk 5 above)
Comment (cesarizu) [inline blueprints/ember-cli-notifications/index.js]: I'll update this. My thinking here was that most addons configure themselves in `ember-cli-build.js` and not in `environment.js`, specially for stuff that has to do with the build process. Selecting which libs to include is part of that process. But then, on the other hand, it's hard to get those values in the component if defined there. Maybe that change belongs to a different PR.

**Comment by cesarizu** [comment]
By looking at the 2.0.0 code [here](https://github.com/Blooie/ember-cli-notifications/blob/v2.0.0/index.js#L13) it seems that it doesn't include `font-awesome` by default. Also the [README](https://github.com/Blooie/ember-cli-notifications/blob/v2.0.0/README.md#font-awesome) states that.

I believe that this should be considered a regression and left `false` by default to avoid breaking SemVer so that existing apps that update don't have errors.

On the other hand I understand that it would be nice for the addon to work out of the box when installed stand-alone. I don't think that asking the user to define `'includeFontAwesome': true` or having an extra `ember install ember-cli-font-awesome` is too much to ask for a developer and if it's clear in the README then I don't see much of a problem there.

**Comment by cesarizu** [comment]
@ynnoj I've updated the README.md to be more clear and keep the same functionality of 2.0.0.

If you still want to keep `includeFontAwesome: true` as default in this version, a different option would be to add a section to the `README.md` with a guide on how to update from 2.0.0 to 2.1.0 that indicates to add `includeFontAwesome: false` to `config/environment.js`.
